first results on properties of p
optimizers/rn2 pull request #25
Opened 2023-09-07 15:08 UTC by dpo

@MohamedLaghdafHABIBOULLAH Please check this carefully.

2023-09-08 18:42 UTC, MohamedLaghdafHABIBOULLAH approved these changes

2023-09-08 18:58 UTC, MohamedLaghdafHABIBOULLAH commented on paper/rn2.tex
> +  Let \Cref{asm:psi,asm:unif-prox-bounded} be satisfied, \(\nabla f(x)\) be bounded over \(\R^n\), and \(B(x) = B(x)^T \succeq 0\).
Why do we need the boundedness of the gradient ?

2023-09-09 19:23 UTC, dpo commented
@MohamedLaghdafHABIBOULLAH I fixed the definition of $\xi$. Again. Could you please check? It was wrong before.

2023-09-10 01:52 UTC, MohamedLaghdafHABIBOULLAH requested changes
In line 402, $\sigma_{max}$ should be equal to max not to min

2023-09-10 02:09 UTC, dpo commented
> In line 402,  should be equal to max not to min

Is that a change in this PR? If not, could you submit another PR?

2023-09-10 02:11 UTC, MohamedLaghdafHABIBOULLAH commented
> 



> > In line 402,  should be equal to max not to min
> 
> Is that a change in this PR? If not, could you submit another PR?

Alright

2023-09-12 02:29 UTC, dpo commented
Thank you.

2023-09-12 02:29 UTC, merged